#!/bin/bash

#replace all P: to OSX equivalent in virtual box config files in this dir and subdirs
find . -type f -name "*.vbox" -exec sed -i '' 's/\/Volumes\/Untitled\/Emulators\//P:\\/g' {} +

#replace all F: to OSX equivalent in virtual box config files in this dir and subdirs
find . -type f -name "*.vbox" -exec sed -i '' 's/\/Volumes\/Untitled\/Games\//F:\\/g' {} +
