#!/bin/bash
. vboxPath.cfg

winDriveOnMac="Untitled"
volumesOnMac="\/Volumes"
winPathOnMac="$volumesOnMac\/$winDriveOnMac"

# remove the windows line ending that's bound to be in the path in the config....
path=$(echo "$vboxVMDirMac" | sed $'s/\r$//' )
cd $path

# make a copy of the .vbox files, suffix with osxbak. We won't use these, just if something goes wrong
find . -name '*.vbox' -print0 | xargs -0 -I {} cp {} {}.osxbak

#replace all P: to OSX equivalent in virtual box config files in this dir and subdirs
find . -type f -name "*.vbox" -exec sed -i '' 's/P:\\/'"$winPathOnMac"'\/Emulators\//g' {} +

#replace all F: to OSX equivalent in virtual box config files in this dir and subdirs
find . -type f -name "*.vbox" -exec sed -i '' 's/F:\\/'"$winPathOnMac"'\/Games\//g' {} +
#this was pond....gone now     find . -type f -name "*.vbox" -exec sed -i '' 's/F:\\/'"$volumesOnMac"'\/Games\//g' {} +

#For VM's that mostly get loaded on windows, change the single C:/Program files ref for the 
#Guest Additions Iso but NOT the 2 references to the guest additions folder on the GUEST
#ie: we're stating windows is the 'primary' host for these images
# (To use BASH variables in BSD SED we must use the '""' syntax)
find . -type f -name "*.vbox" -exec sed -i '' 's/C:\\Program Files\\Oracle\\VirtualBox\\/'"$winPathOnMac"'\/Program Files\/Oracle\/VirtualBox\//g' {} +

#for boot2docker assume osx is the host
find . -type f -name "*.vbox" -exec sed -i '' 's/E:\\Users\\twoode\\.boot2docker\\/\/Users\/twoode\/.boot2docker\//g' {} +

#ditto for ubuntu
find . -type f -name "*.vbox" -exec sed -i '' 's/E:\\Applications\\VirtualBox.app\\Contents\\MacOS\\/\/Applications\/VirtualBox.app\/Contents\/MacOS\//g' {} +

# hijaack this script, years later, to alter a drive path depending on mac (i.e.: this isn't about windows at all)
[[ $(scutil --get HostName) = "typhoon-macos" ]] && gamespath='"\/Volumes\/Untitled\/Games"' || gamespath='"\/Volumes\/Games"'

find . -type f -name "*.vbox" -exec sed -i '' -E 's/hostPath="\/Volumes(\/Untitled)?\/Games"/hostPath='"$gamespath"'/g' {} +


open $vboxAppMac
